---
title: "Student symposium"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Wednesday, December 11, 2019

## Alexandra Roule

*Where the research stands on ADHD and the gut-brain axis*
 
A growing field of literature aims to understand the relationship between the brain and the microbiome of the gut, as well as its significance to mental health (Grenham, Clarke, Cryan, & Dinan, 2011; Sarkar et al., 2016). Attention-deficit hyperactivity disorder (ADHD) is a prevalent neurodevelopmental disorder defined by executive functioning deficits (Kasper, Alderson, & Hudec, 2012; Nigg, 2001), including aberrant reward processing (Aarts et al., 2017). One explanation for reward processing deficits is dysregulation of the reward neural network, particularly the uptake of dopamine (Aarts et al., 2017; Volkow et al., 2010). In the gut, monoamines, which are building blocks for neurotransmitters like dopamine, are formed (Aarts et al., 2017). Given that the microbiome influences reward processing, current research is investigating whether changes in the microbiome targeting the creation of these building blocks may be a feasible intervention for ADHD (Stevens et al., 2019).

## Tyler Warner

*Stimulant use in ADHD: Pathways of activation, immediate effects, and long-term neurological changes*

Stimulants, including methylphenidate and amphetamine, have been shown to effectively reduce symptoms of Attention-Deficit/Hyperactivity Disorder (ADHD) and are strongly recommended by the American Academy of Pediatrics for the treatment of symptoms of ADHD in children 6 years and older.1,2 Positron emission tomography (PET) has been used to show that individuals with ADHD experience lower dopamine receptor binding in the nucleus accumbens compared to controls3, and diffusion tensor imaging (DTI) has shown reduced white matter projections between the nucleus accumbans and regions of the midbrain and cortex4. It is hypothesized that stimulant medication reduces inattentive, hyperactive, and impulsive behaviors by increasing the binding of dopamine (and to a lessor extent, norepinephrine), either by antagonizing synaptic monoamine transporters (methylphenidate) or pre-synaptic vesicular monoamine transporters (amphetamine). However, while the short-term effects of stimulants on children with ADHD have been studied extensively, far less focus has been placed on the effects of long-term use on neurological development in children. At least one study has shown that there are not long-term changes in neurological anatomy5, although more follow-ups from RCTs should be conducted to determine the neurological changes potentially caused by long-term stimulant use.

## Chelsea Mayo

*Exploring the neuropsychology of intellectual disability: Multisystemic and dimensional views of intellectual and adaptive functioning*

Intellectual developmental disorder (IDD), or intellectual disability (ID), is a classifier for a number of neurodevelopmental disorders associated with intellectual and adaptive functioning deficits, and research on this disorder has required an increasingly multilevel and multisystemic approach. Though some known genetic conditions, such as Down Syndrome and Fragile X syndrome, are conceptualized as known causes of ID, these identified genetic abnormalities account for only about a quarter of cases of ID (Lee, Maiman, & Godfrey, 2016; Volk, Chiu, Sharma, & Huganir, 2015). In fact, chromosomal aberrations, single gene mutations, and environmental factors, are just some of the many suspected heterogenous causes of IDD (Iwase et al., 2017; Volk et al., 2015). Extant research on intellectual disabilities has also examined various neurocognitive domains, including memory, inhibition, and cognitive flexibility, in order to illuminate the neurobiology of intellectual disabilities (Pennington, 2009). However, what determines whether a particular gene expression, form of brain plasticity, or type of cognitive functioning constitutes a ‘deficit’ and is therefore indicative of intellectual disability, when intellectual and adaptive functioning comprise spectrums of behavior grounded in the particular societal context in which they are judged? The diagnosis of ID is given usually via a IQ cut-off score of 70, and yet the neuropsychological underpinnings of ID do not so simply map on to these predetermined cutoffs. Thus some scholars are pushing back against research wherein “neuroscience only enters the picture after pathology is taken as fact,” (Altermark, 2014). In contrast to single cognitive deficit models of developmental disorders, future research should pursue how intellectual disability can be better understood as a combination of dimensional differences in multiple cognitive domains. 

## Rachel Level

*The biological basis of learning disabilities in children*

Specific learning disabilities are considered neurologically based, with dysfunction of information processing often attributed as the underlying cause of learning difficulties. However, efforts to understand learning disabilities in children by focusing on specific neurological deficits have failed to identify consistent and stable functional profiles. In this talk, I plan to review and critique the existing neurological literature on learning-related differences between children with learning difficulties and those without learning difficulties. I will conclude by  discussing the limitations of the current neuropsychological research on this topic and exploring potential avenues for future neuropsychological and intervention-based research.

## Tawni Stoop

*Understanding Autism: Social Perception and Underlying Processes*

Autism Spectrum Disorder (ASD) is a neurodevelopmental disorder characterized by deficits in both social emotion processing and experience, social engagement, and rigid thinking or repetitive interests and behaviors (APA, 2013). To date, diagnosis of ASD relies purely on behavioral cues that may overlap with other neurodevelopmental disorders (i.e., Intellectual Disability) or that may not arise until situational demands increase. These symptoms may be identified early in childhood, however in some instances it may not be until behavioral problems have already escalated that proper diagnosis is attained. It is important to determine what other markers may serve as identifiers that can improve diagnosis earlier in childhood. As the Psychology field moves towards finding pathophysiological and biological markers under the RDoC system to improve diagnoses, it is important to take stock of what research exists that can begin to fill in the blanks within this framework for Autism Spectrum Disorder that can serve to improve diagnostic clarity, speed, and accuracy. This talk will briefly review what is already known about the biological processes of ASD and where there are still gaps in knowledge.

## Haruka Notsu

*Neurobiology of psychotherapy*

# Friday, December 13, 2019

## Ryan Kilcullen

*Assessing and Applying Clinically-Relevant and Actionable Findings from Neuroscience to Psychotherapy*

My lab here at PSU primarily focuses on practice-oriented research in psychotherapy. One of the tenets of practice-oriented research is an emphasis on asking research questions that are of genuine interest to clinicians (as opposed to just researchers) and that yield (or strive to yield) actionable findings. That is, the findings from solid practice-oriented research ought to be digestible by clinicians and directly informing their practice. Neuroscience is becoming an increasingly central focus of much clinical psychological research; one would be hard-pressed to attain a grant from a major funding agency like NIMH for a study that doesn’t involve a brain imaging component. As I understand it, the inclusion of neuroscience into the paradigm of clinical psychological research has shed much light on neural correlates and other biological correlates of psychopathology. While this information is crucial to psychiatric research and undoubtedly has had direct  impacts on psychopharmacological advances, I have struggled to see how such research could inform a psychotherapist and his/her psychological interventions. To my pleasant surprise, research has examined this question; for instance, Cappas, Andres-Hyman, & Davidson (2005) posits a “brain-based psychotherapy.” Relatedly, Fonagy (2004) examined among other things how neuroimaging and genetic research can inform case conceptualization in psychotherapy. Recent research is even suggesting that neuroscience can bolster or support certain psychotherapeutic approaches and theories, for instance, the notion that emphases on relational processes in psychotherapy is supported by neuroscience (Schore, 2014). My plan for the symposium would be to summarize briefly this literature, reflect on the viability of this research with regard to improving clinical practice, as well as touching on prominent limitations, shortcomings, and future directs for this brand of interdisciplinary research. 

## Holly Zaharchuk

*What can time frequency analysis tell us about language processing?*

Electroencephalography (EEG) research on language processing typically uses event-related potential (ERP) analyses to measure the neural response to a particular stimulus. Two well-established ERP components, the N400 and P600, index semantic and syntactic integration, respectively. While we know that these components reflect functionally distinct linguistic processes, we do not yet know how these processes combine to form a coherent meaning across an utterance (sentence). Frequency-based analyses of EEG data can help us unpack the level of synchronization across semantic and syntactic processes.

## Daisy Lei

*Word Learning and Consolidation*

Vocabulary acquisition does not stop after one becomes proficient in one native language. Vocabulary knowledge continues across the lifespan and is probably the only cognitive measure that continues to grow after the 20s and remains relatively stable in older adulthood. To that end, what supports novel word learning in adults? According to the complementary learning systems theory (CLS) of word learning (Davis and Gaskell, 2009), offline consolidation (e.g. sleep) is needed for novel words to become incorporated into one’s existing lexicon. EEG may also be used to investigate the lexicalization of novel words. I will present the updated CLS theory (Kumaran, Hassabis, and McClelland, 2016) and results from the neuropsychological literature on novel word learning.

## So Yeon Chun

*Language Impairment and Electroencephalography (EEG)*

Children with Specific Language Impairment (SLI) are known to have deficits in language processing. Some argue that their linguistic deficits are due to idiosyncratic brain functions and the structure. In line with this assumption, this presentation will provide a brief overview of Event-Related Potential (ERP) components and the brain oscillations related to the linguistic factors that may affect language deficits. Specifically, the presentation will review the distinctive EEG patterns of children with SLI and dyslexia.

## Young In Chung and Jacob Martin

*Testing the effectiveness of a fMRI-based neurofeedback training of emotion regulation in borderline personality disorder*

The main objective of the study is to test the effectiveness of a novel fMRI neurofeedback training targeted for down-regulating emotional reactivity to facilitate emotion regulation in individuals with borderline personality disorder (BPD). Emotion regulation is a prominent feature of a number of mental disorders, and has implications for functioning in areas of interpersonal relationships, coping with stress, and capacity to work. Emotion regulation is core to BPD, with many current treatments for BPD emphasizing ways to improve regulatory skills; as such, individuals with BPD are an ideal sample for studying the application of a novel method of providing feedback that indicates ability to regulate emotions. Neurofeedback has been investigated as a non-invasive method to train self-regulation of brain activity, with a potential concomitant change in relevant behavior. The advantage of neurofeedback is that it offers an individual-specific, real-time feedback so that participants can optimize and shape their strategy learning process. The study aims to address two specific objectives: (1) to determine whether individuals with BPD receiving the veritable fMRI neurofeedback, compared to those in the control condition, will learn strategies to decrease their reactivity to socioemotional stimuli, (2) to understand the extent to which improvement in the ability to regulate emotion-related brain regions is correlated with better interpersonal functioning outcome in real life. 

## Leslie Ho

*Neural Networks Underlying Emotions and Task Performance*
	
The processing of emotions involves inter-related cognitive, physiological, and neural systems through which individuals perceive environmental stimuli, attribute meaning to social information, and enact behavioral strategies in order to achieve a goal state. Many studies examining individual differences in task performance distinguish between “cool” and “hot” executive functions. In such experimental paradigms, “hot” executive function requires overt emotion regulation to complete task demands, whereas “cool” executive function is thought to be active during tasks that are not explicitly designed to be emotionally evocative. However, this theoretical approach may inadvertently underplay the additional roles that emotions have in information processing, attention orientation, and memory consolidation, beyond “merely” regulating behavior. This presentation seeks to explore the ways in which emotions are involved in motivational processes that drive learning and task performance, as well as the neural networks involved in the activation of emotions to pursue goal-directed behavior. In their review article, Cardinal, Parkinson, Hall, and Everitt (2002) argue that emotions assist in creating representations of stimulus value, which influences the process of associative learning. Additionally, they argue that emotional processing is a core function of different neural systems that are involved with learning and behavioral planning. 

## Hannah Merseal

*The cognitive neuroscience of musical improvisation*

Musical improvisation, as in jazz, has recently emerged as a means of studying complex creative behavior that occurs in real time. Unlike other musical traditions, improvisers face the unique challenge of spontaneously creating new music while simultaneously executing and integrating multiple cognitive processes, including motor planning, attention, self-monitoring, memory retrieval, decision making, and communication. Despite the challenges of bringing improvisation into an empirical research setting, neuroimaging in combination with behavioral methods offers powerful tools for isolating sub-processes of cognition during improvisation, including more domain-general resources shared with other behaviors such as language production and cognitive control.  
